/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadId = IDL.Nat;
export const Lead = IDL.Record({
  'id' : LeadId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'productInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitLeadResult = IDL.Variant({
  'ok' : LeadId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitLead' : IDL.Func([LeadRequest], [SubmitLeadResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadId = IDL.Nat;
  const Lead = IDL.Record({
    'id' : LeadId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'productInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitLeadResult = IDL.Variant({ 'ok' : LeadId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitLead' : IDL.Func([LeadRequest], [SubmitLeadResult], []),
  });
};

export const init = ({ IDL }) => { return []; };